E2Helper.Descriptions["createPortalPair(vava)"] = "Creates a link pair of portals and returns them in an entity array."
E2Helper.Descriptions["getPortalExit(e:)"] = "Returns the exit portal entity that this portal is paired with."
E2Helper.Descriptions["getPortalSize(e:)"] = "Returns the size of the portal as a vector."
E2Helper.Descriptions["getPortalExitSize(e:)"] = "Returns the size of the portal this is paired with as a vector."
E2Helper.Descriptions["setPortalSize(e:xv2)"] = "Sets the size of the portal, clamped between 0.01 and 10.\nReturns 0 on fail, 1 on success."
E2Helper.Descriptions["setPortalSize(e:nn)"] = E2Helper.Descriptions["setPortalSize(e:xv2)"]
E2Helper.Descriptions["setPortalExitSize(e:xv2)"] = "Sets the size of the portal this is paired with.\nReturns 0 on fail, 1 on success."
E2Helper.Descriptions["setPortalExitSize(e:nn)"] = E2Helper.Descriptions["setPortalExitSize(e:xv2)"]
E2Helper.Descriptions["removePortalPair(e:)"] = "Removes a linked pair of portals, recommended to put in a last() function.\nReturns 0 on fail, 1 on success."